### PR TITLE
support for setting `summary`, `description` field of schema reference

### PR DESCRIPTION
**Pull request by link-duan**
This is a very useful feature when decribing a nested field of an object

### CODE REVIEW

**Comment by link-duan** [comment]
@fenollp 
Could you please merge this PR ? This feature is important for me.

**Comment by fenollp** [comment]
Hi! 
Please prove that it is legal to have fields alongside `$ref` and then add tests showing de/ser/ialization.

**Review by fenollp — CHANGES_REQUESTED** [review]
See comment

**Comment by fenollp** [comment]
Feel free to reopen once you've gotten to https://github.com/getkin/kin-openapi/pull/683#issuecomment-1331001012 :)

**Pull request closed without merging**
