### PR TITLE
Define UUID format for string schema

### PR DESCRIPTION
**Pull request by yaronius**
This fixes error `Validating Swagger failed: Unsupported 'format' value 'uuid'`

### CODE REVIEW

**Comment by fenollp** [comment]
Yeah the spec https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md
says 
> Primitives have an optional modifier property: format. OAS uses several known formats to define in fine detail the data type being used. However, to support documentation needs, the format property is an open string-valued property, and can have any value. Formats such as "email", "uuid", and so on, MAY be used even though undefined by this specification. Types that are not accompanied by a format property follow the type definition in the JSON Schema. Tools that do not recognize a specific format MAY default back to the type alone, as if the format is not specified.

so as resolved on #79 albeit very expeditiously I don't think this lib must validate such formats by default (as opposed to e.g. `date-time`), however I'd love to have the formats defined in-lib and only activated at user's request.

So could you define an exported string constant in https://github.com/getkin/kin-openapi/blob/master/openapi3/schema_formats.go with the name `FormatOfStringForUUIDOfRFC4122`? Or something that has a similarly-easy-to-find-on-godoc-because-sorted prefix.

**Comment by yaronius** [comment]
@fenollp thank you for replying and reasonable remarks, I made changes and now uuid format is optional.

**Comment by fenollp** [comment]
Ah! Sorry I meant for `FormatOfStringForUUIDOfRFC4122` to be the value, not the uuid key :)

**Comment by yaronius** [comment]
@fenollp I see, updated

**Comment by yaronius** [comment]
@fenollp I tested my changes with various schema and I guess this change would not solve the issue with unsupported UUID format because all the supported formats are hardcoded [here](https://github.com/getkin/kin-openapi/blob/master/openapi3/schema.go#L500). I would suggest modifying the default case in `schema.go`:

```
default:
	// Try to check for custom defined formats
	if _, ok := SchemaStringFormats[format]; !ok {
		return unsupportedFormat(format)
	}
```

That works perfectly for cases when we define custom formats and looks flexible to me. What would you say about this?

**Comment by fenollp** [comment]
I believe this is the most correct way indeed! Thanks for taking the time :) 
Add this in and I'll merge the whole thing.

**Comment by yaronius** [comment]
Thanks, changes added

**Comment by fenollp** [comment]
Thank you for your time Zorg! BTW I can easily quote you 90% of this movie (albeit in French) hehe

**Pull request merged**
