### PR TITLE
reproduce incorrect discriminator handling with ValidateRequest

### PR DESCRIPTION
**Pull request by fenollp**
Reproduces #80 
cc #321 

@RiccardoManfrin Could you take a look at this as you've touched discriminator recently please?That'd help a lot :)

### CODE REVIEW

**Comment by RiccardoManfrin** [comment]
From a first look you are missing the "mapping" key which the code I wrote expected all along with the discriminator.
Like so: https://github.com/getkin/kin-openapi/blob/master/openapi3filter/validation_discriminator_test.go#L42

**Comment by fenollp** [comment]
@RiccardoManfrin Thanks! So it turns out `mapping` isn't required. It all boiled down to oneOf v. allOf.

**Comment by ohasanliUW** [comment]
reviving this thread. this PR has not resolved the validation for handling discriminator, as far as I understand. The unit test does not cover negative test cases where validation should fail. I added one locally and it incorrectly passes validation.

**Comment by fenollp** [comment]
@ohasanliUW Please open a PR with this test.

**Pull request merged**
