### PR TITLE
Fix handling recursive refs

### LINKED ISSUE #402: Resolving reference error happens with directories of different depths
Hi. I found the recursive lookup will fail when there are files in directories of different depths.

reporduce: https://github.com/stakme/kin-openapi/commit/cefedea2d71ad4ce07f2739ecbaea4c4f113f9cd

```
> go test github.com/getkin/kin-openapi/openapi3
--- FAIL: TestLoaderReadFromURIFunc (0.00s)
    loader_read_from_uri_func_test.go:20: 
                Error Trace:    loader_read_from_uri_func_test.go:20
                Error:          Received unexpected error:
                                error resolving reference "../openapi.yml#/components/schemas/Bar": open testdata/recursiveRef/components/openapi.yml: no such file or directory
                Test:           TestLoaderReadFromURIFunc
--- FAIL: TestLoaderSupportsRecursiveReference (0.00s)
    loader_recursive_ref_test.go:13: 
                Error Trace:    loader_recursive_ref_test.go:13
                Error:          Received unexpected error:
                                error resolving reference "../openapi.yml#/components/schemas/Bar": open testdata/recursiveRef/components/openapi.yml: no such file or directory
                Test:           TestLoaderSupportsRecursiveReference
FAIL
FAIL    github.com/getkin/kin-openapi/openapi3  0.192s
FAIL
```

It seems that, each time it resolve the reference, it needs to update the `documentPath`.

### PR DESCRIPTION
**Pull request by stakme**
Fix #402

### CODE REVIEW

**Comment by stakme** [comment]
Tests failed with latest release, but this is just what I want to fix... 
Should I create another PR to merge just codes first?

```
panic: error resolving reference "../openapi.yml#/components/schemas/Bar": open recursiveRef/components/openapi.yml: file does not exist [recovered]
	panic: error resolving reference "../openapi.yml#/components/schemas/Bar": open recursiveRef/components/openapi.yml: file does not exist
```

**Comment by stakme** [comment]
created 🚀  #404

**Comment by fenollp** [comment]
Let's merge the fix and tests at the same time. I've pushed a change to the CI that should remove that failure. Please rebase this PR.

**Comment by fenollp** [comment]
Sorry, please rebase again as I had just introduced a typo that disabled the CI completely and quite silently.
https://github.com/getkin/kin-openapi/pull/406
Thanks

**Comment by stakme** [comment]
all checks passed, thank you!

**Pull request merged**
