### PR TITLE
openapi2conv: convert schemaRef for additional props

### PR DESCRIPTION
**Pull request by jayanth-tatina-groww**
Fixes Issue: https://github.com/getkin/kin-openapi/issues/1016.
 
Not sure why additionProperties field is of type openapi3.Schema .Doing a conversion on the ref field

### CODE REVIEW

**Comment by fenollp** [comment]
Thanks!

**Comment by jlsherrill** [comment]
❤️

**Comment by Ulrar** [comment]
Hi, could we maybe get a patch release with this fix in ?
0.128.0 has been broken and I've had to manually bump renovate's branch down to 0.127.0 every week since, I'll be really really glad once the fix is released

**Comment by fenollp** [comment]
Done: https://github.com/getkin/kin-openapi/releases/tag/v0.129.0 :)

**Pull request merged**
