### PR TITLE
fix: thoroughly replace yaml packages with oasdiff's

### PR DESCRIPTION
**Pull request by fenollp**

### CODE REVIEW

**Comment by fenollp** [comment]
```
     kin-openapi.git actually-replace-invopop λ go mod tidy && go mod verify
go: finding module for package github.com/oasdiff/yaml3
go: finding module for package github.com/oasdiff/yaml
go: found github.com/oasdiff/yaml in github.com/oasdiff/yaml v0.0.0-20240920191703-3e5a9fb5bdf3
go: found github.com/oasdiff/yaml3 in github.com/oasdiff/yaml3 v0.0.0-20240920135353-c185dc6ea7c6
go: github.com/getkin/kin-openapi/cmd/validate imports
	github.com/oasdiff/yaml: github.com/oasdiff/yaml@v0.0.0-20240920191703-3e5a9fb5bdf3: parsing go.mod:
	module declares its path as: github.com/invopop/yaml
	        but was required as: github.com/oasdiff/yaml
1    kin-openapi.git actually-replace-invopop λ 
```

@reuvenharrison Could you update your yaml packages's `mod` path so the above no longer reproduces please?

**Comment by ccoVeille** [comment]
The current oasdiff is the fork from the one you replace

The one you replace was already a fork from another one.

The oasdiff README doesn't mention (yet) its purpose and why you decided to create your fork.

So I'm asking here, why such a fork? And why changing here

**Comment by fenollp** [comment]
Hi @ccoVeille 
Please see @reuvenharrison's past PRs to understand how his fork of yaml packages got in there: https://github.com/getkin/kin-openapi/pulls?q=sort%3Aupdated-desc+is%3Apr+author%3Areuvenharrison+is%3Amerged
Also note that I do not maintain such forks.
As to why the changes in this PR, please see the linked issue: https://github.com/getkin/kin-openapi/issues/1036

Feel free to pursue the conversation here if you feel the need to.

**Comment by ccoVeille** [comment]
Thank you for the explanations.

It's now clearer

**Comment by ccoVeille** [comment]
Maybe the README of oassdiff could be updated to explain that.

Do you want me to open an issue on the oasdiff/yaml repository pointing our discussion?

**Comment by reuvenharrison** [comment]
I will update the readme to clarify this. Thanks.

**Comment by reuvenharrison** [comment]
See https://github.com/getkin/kin-openapi/pull/1038

**Comment by fenollp** [comment]
Fixed in https://github.com/getkin/kin-openapi/pull/1038

**Pull request closed without merging**
