### PR TITLE
Handle port number variable of servers given to gorillamux.NewRouter

### PR DESCRIPTION
**Pull request by fenollp**
fixes https://github.com/getkin/kin-openapi/issues/367
closes https://github.com/getkin/kin-openapi/pull/523

### CODE REVIEW

**Comment by slessard** [comment]
I don't think this change will work with the below server config. (I'm still a bit new to forking and trying to figure out the best way to get your branch into my fork to test it out. Sorry, I haven't yet figured that out.)

```
		{URL: "{server}", Variables: map[string]*openapi3.ServerVariable{
			"server": {Default: "/"},
		}},
```

**Comment by slessard** [comment]
OK, I figured out the forking/remote/branching thing. I pulled your issue367 branch, added the server config from my previous message and confirmed the unit tests fails for that server config.

```
=== RUN   TestRouter
    router_test.go:176: 
        	Error Trace:	router_test.go:176
        	Error:      	Received unexpected error:
        	            	mux: path must start with a slash, got "{server}/partial"
        	Test:       	TestRouter
--- FAIL: TestRouter (0.00s)
```

**Comment by fenollp** [comment]
I see your point and thanks for thinking of this. I would say this is a bit off topic with regards to #367 but if that's your use case we might as well address it.

I am tempted to say: let's handle this as another special case. If server URL is just a variable (or a var + a trailing / e.g. `{server}/`), then just don't append to that `servers` slice. The following test `len(servers) == 0` should handle it from there.

**Comment by fenollp** [comment]
Actually my hunch was wrong but this works:
```diff
diff --git a/routers/gorillamux/router.go b/routers/gorillamux/router.go
index 8490992..999909b 100644
--- a/routers/gorillamux/router.go
+++ b/routers/gorillamux/router.go
@@ -47,6 +47,16 @@ func NewRouter(doc *openapi3.T) (routers.Router, error) {
 	servers := make([]srv, 0, len(doc.Servers))
 	for _, server := range doc.Servers {
 		serverURL := server.URL
+
+		if serverURL == "{server}" { // TODO
+			servers = append(servers, srv{
+				base:   server.Variables["server"].Default,
+				server: server,
+				// TODO: varsUpdater to set vars["server"] = LHS of actual URL that isn't srv.base
+			})
+			continue
+		}
+
 		var schemes []string
 		if strings.Contains(serverURL, "://") {
 			scheme0 := strings.Split(serverURL, "://")[0]
diff --git a/routers/gorillamux/router_test.go b/routers/gorillamux/router_test.go
index 7da301e..1906249 100644
--- a/routers/gorillamux/router_test.go
+++ b/routers/gorillamux/router_test.go
@@ -187,6 +187,17 @@ func TestRouter(t *testing.T) {
 		"port": "8000",
 	})
 
+	doc.Servers = []*openapi3.Server{
+		{URL: "{server}", Variables: map[string]*openapi3.ServerVariable{
+			"server": {Default: "/api/v1"},
+		}},
+	}
+	err = doc.Validate(context.Background())
+	require.NoError(t, err)
+	r, err = NewRouter(doc)
+	require.NoError(t, err)
+	expect(r, http.MethodGet, "https://myserver/api/v1/hello", helloGET, nil)
+
 	{
 		uri := "https://www.example.com/api/v1/onlyGET"
 		expect(r, http.MethodGet, uri, helloGET, nil)
```

I encourage you to work on this and I'll help for sure. I'd also like that we close the subject on the issue at hand first before moving on to other things :)

**Comment by slessard** [comment]
I didn't fully understand your comment...
```go
// TODO: varsUpdater to set vars["server"] = LHS of actual URL that isn't srv.base
```
because without access to `req.URL.String()` I don't know what is or hot to get the actual URL.

Regardless I took a shot at implementing a solution according to my understanding of your suggestion. This patch passes the unit tests, but somehow I feel it is incorrect. What do you think?

```diff
diff --git a/routers/gorillamux/router.go b/routers/gorillamux/router.go
index 8490992..6817b4b 100644
--- a/routers/gorillamux/router.go
+++ b/routers/gorillamux/router.go
@@ -9,6 +9,7 @@ package gorillamux
 import (
 	"net/http"
 	"net/url"
+	"regexp"
 	"sort"
 	"strings"
 
@@ -47,6 +48,26 @@ func NewRouter(doc *openapi3.T) (routers.Router, error) {
 	servers := make([]srv, 0, len(doc.Servers))
 	for _, server := range doc.Servers {
 		serverURL := server.URL
+		singleVariableMatcher := regexp.MustCompile(`^\{([^\}]+)\}$`)
+		submatch := singleVariableMatcher.FindStringSubmatch(serverURL)
+		if submatch != nil {
+			serverVariable := submatch[1]
+			serverValue := server.Variables[serverVariable].Default
+			serverURL = strings.ReplaceAll(serverURL, "{"+serverVariable+"}", serverValue)
+			lhs := strings.TrimSuffix(serverURL, server.Variables[serverVariable].Default)
+			servers = append(servers, srv{
+				base:   server.Variables[serverVariable].Default,
+				server: server,
+				varsUpdater: func(vars map[string]string) {
+					// TODO: varsUpdater to set vars["server"] = LHS of actual URL that isn't srv.base
+					if lhs != "" {
+						vars[serverVariable] = lhs
+					}
+				},
+			})
+			continue
+		}
+
 		var schemes []string
 		if strings.Contains(serverURL, "://") {
 			scheme0 := strings.Split(serverURL, "://")[0]
diff --git a/routers/gorillamux/router_test.go b/routers/gorillamux/router_test.go
index 7da301e..1906249 100644
--- a/routers/gorillamux/router_test.go
+++ b/routers/gorillamux/router_test.go
@@ -187,6 +187,17 @@ func TestRouter(t *testing.T) {
 		"port": "8000",
 	})
 
+	doc.Servers = []*openapi3.Server{
+		{URL: "{server}", Variables: map[string]*openapi3.ServerVariable{
+			"server": {Default: "/api/v1"},
+		}},
+	}
+	err = doc.Validate(context.Background())
+	require.NoError(t, err)
+	r, err = NewRouter(doc)
+	require.NoError(t, err)
+	expect(r, http.MethodGet, "https://myserver/api/v1/hello", helloGET, nil)
+
 	{
 		uri := "https://www.example.com/api/v1/onlyGET"
 		expect(r, http.MethodGet, uri, helloGET, nil)
-- 
```

**Comment by slessard** [comment]
@fenollp Is there anything I can do to more fully address your concerns with the patch I proposed above?

(I'll be out on vacation next week so please expect very delayed responses.)

**Pull request merged**
